- name: Install Certbot and dependencies
  ansible.builtin.apt:
    name:
      - certbot
      - python3-certbot
    update_cache: true
    state: present

- name: Ensure .well-known directory exists for LetsEncrypt webroot challenge
  ansible.builtin.file:
    path: "{{ letsencrypt_webroot }}/.well-known/acme-challenge"
    state: directory
    owner: www-data
    group: www-data
    mode: "0755"

- name: Obtain Let's Encrypt certificate using webroot plugin
  ansible.builtin.command: >
    certbot certonly
    --webroot
    -w {{ letsencrypt_webroot }}
    -d {{ item }}
    --email {{ letsencrypt_email }}
    --agree-tos
    --non-interactive
  loop: "{{ letsencrypt_domains }}"
  register: certbot_result
  changed_when: "'Certificate not yet due for renewal' not in certbot_result.stdout"

- name: Symlink certbot cert/key into nginx expected paths
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
  loop:
    - { src: "{{ letsencrypt_key_path }}", dest: "{{ nginx_quic_ssl_key_path }}" }
    - { src: "{{ letsencrypt_cert_path }}", dest: "{{ nginx_quic_ssl_cert_path }}" }
  notify: Reload nginx

- name: Render final nginx config using Let's Encrypt certs
  ansible.builtin.template:
    src: nginx-certbot.conf.j2
    dest: "{{ nginx_quic_prefix }}/nginx.conf"
    owner: root
    group: root
    mode: "0644"
  notify: Reload nginx
